server:
  port: 8072
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: gatewayserver
  config:
    import: configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
      - id: AccountsMicroservice
        uri: lb://ACCOUNTS
        predicates:
        - Path=/customerexecutive/**
        filters:
        - RewritePath=/customerexecutive/accounts/(?<remaining>.*), /$\{remaining}
      - id: LoansMicroservice
        uri: lb://LOANS
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/loans/(?<remaining>.*), /$\{remaining}
      - id: CardsMicroservice
        uri: lb://CARDS
        predicates:
        - Path=/support/**
        filters:
        - RewritePath=/support/cards/(?<remaining>.*), /$\{remaining}